[package]
name = "junit-report"
version = "0.8.1"
authors = ["Pascal Bach <pascal.bach@nextrem.ch>"]
description = "Create JUnit compatible XML reports."
license = "MIT"
repository = "https://github.com/bachp/junit-report-rs"
keywords = ["junit", "xunit", "xml", "report"]
readme = "README.md"
edition = "2021"

[dependencies]
derive-getters = "0.2.0"
quick-xml = "0.25.0"
strip-ansi-escapes = "0.1.0"
time = { version = "0.3.4", features = ["formatting", "macros"] }

[dev-dependencies]
doc-comment = "0.3.3"
once_cell = "1.14"
regex = "1.6"
